export default function Placeholder() {
  return (
    <main className="mx-auto flex min-h-dvh max-w-2xl flex-col justify-center gap-8 px-6 py-16">
      <p className="text-notice border-notice/40 bg-notice/5 w-fit border px-3 py-1 text-xs tracking-widest uppercase">
        Synthetic data
      </p>
      <div className="space-y-4">
        <h1 className="text-3xl font-semibold tracking-tight">demogym</h1>
        <p className="text-ink-dim leading-relaxed">
          Member-retention tooling for a fictional gym operator. Every site, member and entry in this
          prototype was generated by code in the repository. No real operator and no real member
          appears anywhere in it.
        </p>
        <p className="text-ink-dim leading-relaxed">
          Nothing is built yet. This page exists to prove the deployment and the access gate work
          before there is anything to deploy.
        </p>
      </div>
      <dl className="border-rule divide-rule divide-y border-t text-sm">
        <div className="flex justify-between gap-4 py-3">
          <dt className="text-ink-dim">Next</dt>
          <dd>The estate screen, one row per site</dd>
        </div>
        <div className="flex justify-between gap-4 py-3">
          <dt className="text-ink-dim">Then</dt>
          <dd>The at-risk queue, and the drafting controls on it</dd>
        </div>
      </dl>
    </main>
  );
}
