import Contents from "./Contents";
import Pairs from "./Pairs";
import Note from "./Note";
import Section from "./Section";
import Steps from "./Steps";
import { ABSENCES } from "./absences";
import { FEEDS } from "./feeds";
import { LEFT_OUT } from "./leftOut";

const BEFORE_IT_RUNS = [
  "A Data Protection Impact Assessment. Profiling at scale, on data of this kind, is squarely what one is for.",
  "A lawful basis that holds for the profiling, not only for holding the attendance record in the first place.",
  "A documented retention period for scores and drafts, which are new personal data this system creates rather than data it was handed.",
  "A route for a member to object to being profiled, and a system that honours it rather than a policy that mentions it.",
];

const FIRST_WEEK = [
  "Get an entry export out of the access control system, one row per scan, covering the last six months. Everything else waits on this, and it is usually a CSV long before it is an API.",
  "Join it to the membership record and count the scans that match no member. That number is the real condition of the data, and it is never zero.",
  "Run the scorer over the real history and look at the band counts. Thresholds tuned against invented members are a starting point, not an answer.",
  "Sit with whoever runs a site and read the queue with them. They know which of those members moved away, which is on holiday and which one they already rang. That hour is worth more than another week of tuning.",
  "Open the Data Protection Impact Assessment, because it decides what the system is allowed to do and there is no sense building past it.",
];

/**
 * The page that says what this is not. It is prose about the system rather than a
 * reading of it, so nothing here is fetched and no figure is hardcoded from a seed.
 */
export default function RealData() {
  return (
    <div className="max-w-4xl space-y-8">
      <div>
        <h1 className="text-2xl font-semibold tracking-tight">Running this on real data</h1>
        <p className="text-ink-dim mt-2 max-w-3xl text-sm leading-relaxed">
          What this prototype does not do, what a real deployment would connect to, where the law
          sits, and what the first week would actually contain. The limitations are part of the
          deliverable, so they are written down here rather than left to a conversation.
        </p>
      </div>

      <Contents />

      <Section id="what-this-is">
        <p>
          Every figure in demogym is invented. The sites, the members, the entry records and the
          equipment were generated by a script that is committed alongside the rest of it, and no
          real operator, site or member appears anywhere. Nothing is sent to anybody: there is no
          email, no SMS and no messaging integration. A model drafts, a person decides, and the
          decision is recorded.
        </p>
        <p>
          The estate is small deliberately. Six sites averaging fifty members is not a viable
          business. It is a size at which the queue can be read end to end by one person and every
          number on screen can be checked by hand, and the rules behind it work the same at a
          hundred times the size. The demonstration is the reasoning, not the row count.
        </p>
      </Section>

      <Section id="what-it-would-connect-to">
        <Pairs items={FEEDS} />
        <p>
          Replacing the generator with those feeds is the first work a real deployment would do.
          Nothing else would have to move. The scorer reads rows out of a table and does not care
          who wrote them, which is the property that makes swapping the source a data engineering
          job rather than a rewrite.
        </p>
      </Section>

      <Section id="what-this-does-not-do">
        <Pairs items={ABSENCES} />
      </Section>

      <Section id="left-out">
        <p>
          Each of these was considered and cut because the data behind it is not something an
          operator certainly has. Anything resting on hardware they might not own, or on a member
          remembering to do something, came out. What each would add is worth knowing, because
          together they are the shape of a second phase.
        </p>
        <Pairs items={LEFT_OUT} />
      </Section>

      <Section id="narrower-claims">
        <p>
          Two things this system can fairly say about itself are narrower than they first sound.
          Both are written here rather than left to be discovered.
        </p>

        <Note statement="Nothing reaching the model is free text, but the system does accept free text.">
          No prompt this system can build contains anything a person typed. Tone, length and offer
          come from dropdowns, and every fact in a prompt was computed by code that can be read. The
          body a reviewer edits before approving is different: that is typed by a person. It is
          bounded in length where it enters, stored beside what the model wrote rather than over it,
          and shown against it. It never reaches a model. The narrow claim is true and the wide one
          is not, so the wide one is not made.
        </Note>

        <Note statement="The briefing's rule against claiming a cause is held by a prompt.">
          A briefing is instructed, in terms, to state any link between attendance and equipment as
          something to check rather than as a finding. There is no check in code that it obeyed, and
          there could not easily be one. What exists is the instruction and a person reading the
          output: every link across all six briefings was read and quoted when the feature was built,
          and none of them asserted a cause. On a real deployment that is a review step, not a
          guarantee.
        </Note>
      </Section>

      <Section id="regulatory-position">
        <p>
          Gym attendance on its own is ordinary personal data. Combined with the health
          questionnaires, body composition readings or injury notes an operator usually also holds,
          it becomes special category data under Article 9 of the UK GDPR. Inferring that a member is
          disengaging, and then acting on that inference, is profiling.
        </p>
        <p>Four things a real deployment needs before it runs:</p>
        <Steps items={BEFORE_IT_RUNS} />
        <p>
          This shapes what the feature is allowed to do rather than sitting beside it. It is cheaper
          to design around at the start than to retrofit, which is why it is on this page instead of
          in a footnote.
        </p>
      </Section>

      <Section id="first-week">
        <p>
          What the first week would actually contain. None of it is model work, and most of it is
          finding out what the data is really like.
        </p>
        <Steps items={FIRST_WEEK} />
        <p>
          Nothing is sent in the first week. The question it answers is whether the queue is worth
          working at all, and that is settled by reading it with the people who would work it.
        </p>
      </Section>

      <Section id="still-open">
        <Note statement="The gap reading has no minimum-data guard.">
          The decay ratio is protected from thin history: below a baseline of one visit a week it
          does not govern at all, because a ratio built on two visits is noise. The typical gap has
          no equivalent. A member with two visits a day apart has a median gap of one day, so a month
          of silence reads as thirty times their usual. This dataset does not produce the case,
          because members here train on a small set of spaced days rather than by an independent draw
          each morning. Real data would produce it. The options are a minimum number of gaps before
          the reading governs, or a floor under the typical gap, and neither is decided.
        </Note>

        <Note statement="Which model should write these.">
          One model is pinned by ID so that runs are reproducible. Whether a cheaper or a larger one
          holds the briefing constraint better is a question for measurement rather than assumption,
          and it has not been measured yet.
        </Note>
      </Section>
    </div>
  );
}
