/**
 * The honesty label, on every page.
 *
 * Solid and dark rather than a tinted notice, so it survives being cropped into a
 * screenshot and cannot be mistaken for decoration. Plausible invented figures
 * without this are indistinguishable from fabricated evidence.
 */
export default function SyntheticDataStrip() {
  return (
    <div className="bg-strip text-strip-ink border-marker border-l-4">
      <p className="mx-auto max-w-7xl px-4 py-2 text-xs leading-snug sm:px-6">
        <span className="text-marker font-medium tracking-wider uppercase">Synthetic data</span>
        <span className="mx-2 hidden sm:inline">/</span>
        <span className="block sm:inline">
          Every figure here was generated by code in this repository.
          <span className="hidden sm:inline">
            {" "}
            No real operator, member or site appears anywhere in it, and nothing is sent to
            anybody.
          </span>
        </span>
      </p>
    </div>
  );
}
